#!/usr/bin/env node
'use strict';

require('shelljs/global')
const os = require('os')
const path = require('path')
const open = require('open')
const ip = require('ip')
const qrcode = require('qrcode-terminal')
const portfinder = require('portfinder')
const alert = require('alert-node')

const http = require('http')
const connect = require('connect')
const serveStatic = require('serve-static')
const serveIndex = require('serve-index')
const simpleGet = require('simple-get')

const share_dir = path.join(os.homedir(), 'share-dir')
mkdir('-p', share_dir)

touch(path.join(share_dir, '请在此处放置需要共享的文件.txt'))

portfinder.getPort(function (err, port) {

  const app = connect()

  app
    .use(function (req, res, next) {
      res.setHeader("Access-Control-Allow-Origin", "*")
      next()
    })
    .use(serveStatic(share_dir, { 'index': ['index.html'] }))
    .use(serveIndex(share_dir, { 'icons': true }))

  http
    .createServer(app)
    .listen(port, function () {
      const uri = `${ip.address()}:${port}` 
      console.log(`Static server start up at '${share_dir}'.`)
      console.log(`Listen at ${uri}.`)
      qrcode.generate(`http://${uri}`, code => {
        console.log(code)
        open(share_dir)
      })


      if (os.platform() === 'win32') {
        simpleGet({ url: `http://${uri}`, timeout: 3e3 }, (err, res) => {
          if (err) {
            alert('网络受限', '若弹出防火墙窗口，请允许程序外网访问。若没有弹出，请手动在 “控制面板”->“系统和安全”->“windows防火墙” 中为程序开启外网访问权限。')
          }
        })
      }

    })

})

